name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Test
        run: nix develop .#ci --command -- bash -c "mix do local.hex --force + local.rebar --force + deps.get; mix test"
        env:
          PGHOST: localhost
      - name: Containerise
        run: nix build .#dockerImage
