name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Start database
        run: nix develop .#ci --command -- bash -c "postgres-start; createuser -d postgres"
      - name: Cache mix dependencies fetched for test
        uses: actions/cache@v3
        with:
          key: hex-dir
          path: |
            ~/.hex
      - name: Test
        run: nix develop .#ci --command -- bash -c "mix do local.hex --force + local.rebar --force + deps.get; mix test"
        env:
          PGHOST: localhost
  containerise:
    name: Containerise
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Build container
        run: nix build .#dockerImage
