name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Start database
        run: nix develop --command -- bash -c "postgres-start; createuser -d postgres"
      - name: Test
        run: nix develop --command -- bash -c "mix do local.hex --force + local.rebar --force + deps.get; mix test"
      - name: Containerise
        run: nix build .#dockerImage
