name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Start database
        run: nix develop .#ci --command -- bash -c "postgres-start; createuser -d postgres"
      - name: Test
        run:
          - nix
          - develop
          - .#ci 
          - --command
          - -- 
          - bash
          - -ec
          - |-
            mkdir deps
            mkdir -p _build/test/lib
            while read -r -d ':' lib
            do
              for dir in "$lib/"/*
              do
                dest="$(basename "$dir" | cut -d '-' -f1)"
                build_dir="_build/test/lib/$dest"
                ln -sfv "$dir" "$build_dir"
                ln -sfv "$dir" "deps/$dest"
              done
            done <<< "$ERL_LIBS:"
            mix do deps.loadpaths --no-deps-check, test
        env:
          PGHOST: localhost
  containerise:
    name: Containerise
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Build container
        run: nix build .#dockerImage
      - name: Load it up
        run: docker load < result
