name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    env:
      PGHOST: localhost
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Start database
        run: nix develop .#ci --command -- bash -c "postgres-start; createuser -d postgres"
      - name: Test
        run: nix develop .#ci --command -- ci-run-tests
  containerise:
    name: Containerise
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Build container
        run: nix build .#dockerImage
      - name: Load it up
        run: docker load < result
